version: '3.8'

services:
  db:
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    image: postgres:15.3
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    image: dpage/pgadmin4:7.4
    ports:
      - "5050:80"
    restart: unless-stopped
    volumes:
      - pgadmin:/var/lib/pgadmin


volumes:
  pgadmin:
  pgdata: