FROM python:3.10 AS dependencies
WORKDIR /usr/src/app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

FROM dependencies as code
COPY dataload.py ./
CMD ["python", "dataload.py"]