version: '3.8'

services:
  dataload:
    build: 
      dockerfile: Dockerfile.dataload
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - dataload:/usr/src/app/dataload-refresh

  db:
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    image: postgres:15.3
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    image: dpage/pgadmin4:7.4
    ports:
      - "5050:80"
    restart: unless-stopped
    volumes:
      - pgadmin:/var/lib/pgadmin


volumes:
  dataload:
  pgadmin:
  pgdata: